//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncidentCalendar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidents
    {
        public System.Guid Id { get; set; }
        public System.Guid ServiceId { get; set; }
        public System.DateTime DateStarted { get; set; }
        public Nullable<System.DateTime> DateEnded { get; set; }
        public string Description { get; set; }
        public int IncidentType { get; set; }
    
        public virtual Services Services { get; set; }
    }
}
